version: '3'
services:
  kong-database:
    image: postgres:9.6
    container_name: kong-database
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-kong}
      POSTGRES_USER: ${POSTGRES_USER:-kong}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-kong}
    volumes:
      - kong-db:/var/lib/postgresql/data
    networks:
      - kong-net

  kong-migrations:
    image: kong:3.3.1
    container_name: kong-migrations
    command: kong migrations bootstrap
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: ${POSTGRES_USER:-kong}
      KONG_PG_PASSWORD: ${POSTGRES_PASSWORD:-kong}
      KONG_PG_DATABASE: ${POSTGRES_DB:-kong}
    depends_on:
      - kong-database
    networks:
      - kong-net

  kong:
    image: kong:3.3.1
    container_name: kong
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: ${POSTGRES_USER:-kong}
      KONG_PG_PASSWORD: ${POSTGRES_PASSWORD:-kong}
      KONG_PG_DATABASE: ${POSTGRES_DB:-kong}
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000
    depends_on:
      - kong-migrations
    networks:
      - kong-net

  konga:
    platform: linux/x86_64
    image: pantsel/konga:latest
    container_name: konga
    ports:
      - "1337:1337"
    environment:
      TOKEN_SECRET: "1234567890" # Replace with your own secret token
      DB_ADAPTER: "postgres"
      DB_HOST: "kong-database"
      DB_USER: ${POSTGRES_USER:-kong}
      DB_PASSWORD:  ${POSTGRES_PASSWORD:-kong}
      DB_DATABASE:  ${POSTGRES_DB:-kong}
    links:
      - kong:kong
    depends_on:
      - kong-database
    networks:
      - kong-net

networks:
  kong-net:
    external: true

volumes:
  kong-db:
